#!/bin/bash

# A script to automatically change the global theme of KDE Plasma based on the
# time of day. It utilizes KDE's built-in night color feature to determine
# whether it is day or night. If the current color temperature deviates from
# the default temperature it is considered night. Otherwise it is considered
# day. The script is intended to be run on startup and then to be left running

# Author: Dmitriy Safiullin
# Date: 2023.12.30


light_theme="org.kde.breeze.desktop"
dark_theme="org.kde.breezedark.desktop"
change_theme_command="plasma-apply-lookandfeel -a"

default_temp=6500
last_theme_file="$HOME/.config/auto-knight/last_theme"

interface="org.freedesktop.DBus.Properties"
member="PropertiesChanged"
path="/ColorCorrect"
arg0="org.kde.kwin.ColorCorrect"

function set_theme() {
    # Set the theme and save it to the last theme file
    $change_theme_command "$1"
    echo "$1" > "$last_theme_file"
}

# Initialize the theme from KWins current color temperature
if [[ "$(qdbus-qt5 org.kde.KWin /ColorCorrect org.kde.kwin.ColorCorrect.currentTemperature)" == "$default_temp" ]]; then
    set_theme "$light_theme"
else
    set_theme "$dark_theme"
fi

# Detect signal from KWin when the color temperature changes
dbus-monitor --session "type='signal',interface='$interface',member='$member',path='$path',arg0='$arg0'" |
    grep --line-buffered -A 1 "currentTemperature" |
    while read -r line; do
        # Check if the current color temperature is the default temperature. Change the theme
        # unless the current theme has already been set to the correct one.
        if [[ "$line" == *"$default_temp"* ]]; then
            if [[ "$(cat "$last_theme_file")" != "$light_theme" ]]; then
                set_theme "$light_theme"
            fi
        else
            if [[ "$(cat "$last_theme_file")" != "$dark_theme" ]]; then
                set_theme "$dark_theme"
            fi
        fi
    done
