#!/bin/bash

interface="org.freedesktop.login1.Manager"
member="PrepareForSleep"

pause_media() {
    playerctl --all-players pause
}

dbus-monitor --system "type='signal',interface='$interface',member='$member'" |
    while read -r line; do
        case "$line" in
        *"boolean"*"true"*) pause_media ;;
        esac
    done
